In [5]:
# import necessary libraries
import pandas as pd
import os
import glob

In [38]:
data_path = os.getcwd() + '\\data_raw\\'

def make_dfs(path):
    # use glob to get all the csv files in the folder
    csv_files = glob.glob(os.path.join(path, '*.csv'))

    age_df_list = []
    income_df_list = []

    for filename in csv_files:
        l = filename.split('.')[0].split('\\')[-1].split('_')[1::]

        df = pd.read_csv(filename, skiprows=4)
        df['Metric'] = l[1]
        df['Year'] = l[2]

        if l[0] == 'age':
            age_df_list.append(df)
        elif l[0] == 'income':
            income_df_list.append(df)

    df_age = pd.concat(age_df_list, axis=0)
    df_income = pd.concat(income_df_list, axis=0)

    return [df_age, df_income]

dfs = make_dfs(data_path)

df_age = dfs[0]
df_income = dfs[1]

In [40]:
df_income

,Selected Geographies,200000-Max,Negative Income,No Income,20001-40000,60001-80000,80001-120000,120001-160000,160001-200000,1-20000,400001-60000,Metric,Year
0,Los Angeles County (North/Unincorporated)--Cas...,4.0,0,3.0,2,3,3,3,3.0,2,3,np,2015
1,Los Angeles County (Northwest)--Santa Clarita ...,4.0,0,2.0,2,2,3,3,4.0,2,3,np,2015
2,Los Angeles County (North Central)--Lancaster ...,4.0,0,2.0,3,4,3,3,3.0,2,3,np,2015
3,Los Angeles County (North Central)--Palmdale C...,4.0,0,2.0,3,3,4,4,4.0,2,3,np,2015
4,Los Angeles County (North)--LA City (Northwest...,3.0,0,2.0,2,3,3,3,3.0,2,3,np,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,Riverside County (Northwest)--Riverside City (...,436.0,299,29.0,705,569,690,387,128.0,657,818,rntp,2019
11,Riverside County (West Central)--Corona City (...,231.0,532,0.0,625,369,335,206,192.0,284,664,rntp,2019
12,Riverside County (West Central)--Corona (North...,408.0,675,0.0,871,941,478,379,105.0,796,728,rntp,2019
13,Riverside County (Northwest)--Jurupa Valley & ...,492.0,0,695.0,718,349,466,556,15.0,666,542,rntp,2019
14,"Riverside County--Palm Desert, La Quinta (West...",171.0,188,871.0,561,432,390,251,206.0,422,379,rntp,2019