In [1]:
from pathlib import Path

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
import matplotlib.pylab as plt
from dmba import plotDecisionTree, classificationSummary, regressionSummary

In [2]:
document_list = ['Raw_Data/LA_NP_2015.csv','Raw_Data/OC_NP_2015.csv','Raw_Data/Rv_NP_2015.csv', 'Raw_Data/LA_NP_2016.csv','Raw_Data/OC_NP_2016.csv','Raw_Data/Rv_NP_2016.csv','Raw_Data/LA_NP_2017.csv','Raw_Data/OC_NP_2017.csv','Raw_Data/Rv_NP_2017.csv',
                 'Raw_Data/LA_NP_2018.csv','Raw_Data/OC_NP_2018.csv','Raw_Data/Rv_NP_2018.csv',
                 'Raw_Data/LA_NP_2019.csv','Raw_Data/OC_NP_2019.csv','Raw_Data/Rv_NP_2019.csv'
                 ]
year_list = [2015,2016,2017,2018,2019]

In [3]:
df = pd.DataFrame()
for year in year_list:
    for excel in document_list:
        df_temp = pd.read_csv(excel, skiprows=4)
        if str(year) in excel:
            df_temp['year'] = year
            df = df.append(df_temp)

In [4]:
df

,Selected Geographies,200000-Max,Negative Income,No Income,20001-40000,60001-80000,80001-120000,120001-160000,160001-200000,1-20000,400001-60000,year
0,Los Angeles County (North/Unincorporated)--Cas...,4.0,0,3.0,2,3,3,3,3.0,2,3,2015
1,Los Angeles County (Northwest)--Santa Clarita ...,4.0,0,2.0,2,2,3,3,4.0,2,3,2015
2,Los Angeles County (North Central)--Lancaster ...,4.0,0,2.0,3,4,3,3,3.0,2,3,2015
3,Los Angeles County (North Central)--Palmdale C...,4.0,0,2.0,3,3,4,4,4.0,2,3,2015
4,Los Angeles County (North)--LA City (Northwest...,3.0,0,2.0,2,3,3,3,3.0,2,3,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
10,Riverside County (Northwest)--Riverside City (...,3.0,0,1.0,3,3,4,4,3.0,2,3,2019
11,Riverside County (West Central)--Corona City (...,4.0,0,1.0,2,3,3,4,4.0,3,3,2019
12,Riverside County (West Central)--Corona (North...,4.0,0,1.0,3,3,3,4,4.0,2,3,2019
13,Riverside County (Northwest)--Jurupa Valley & ...,5.0,0,3.0,4,4,4,4,4.0,2,4,2019
14,"Riverside County--Palm Desert, La Quinta (West...",2.0,0,1.0,2,2,2,2,2.0,1,2,2019

In [ ]:
df.to_csv('H')